### ISSUE TITLE
Codecourse Contrast - Black text

### ISSUE THREAD

**Issue by OwenMelbz** [rainglow/sublime#2]
Hey!

I've noticed a couple of issues with the codecourse theme which hopefully can get sorted :D

Certain keywords seem to appear in black text and cannot be read.

e.g in PHP files these code comments break

![__sites_1st-choice-spares_database_migrations_2018_01_08_164005_adding_submitted_flag_to_requests_php_ _1st_choice](https://user-images.githubusercontent.com/1094740/34681285-4be57ed4-f493-11e7-8df9-31f7ac143033.jpg)

![__sites_1st-choice-spares_database_migrations_2018_01_08_164005_adding_submitted_flag_to_requests_php_ _1st_choice](https://user-images.githubusercontent.com/1094740/34681295-526ff54a-f493-11e7-87db-e0790029707a.jpg)

I first noticed this though in bash scripts e.g

![___zshrc_ _1st_choice](https://user-images.githubusercontent.com/1094740/34681340-778ff104-f493-11e7-9579-aceb77b861a5.jpg)

You can see its various keywords that are broken on

![___zshrc_ _1st_choice](https://user-images.githubusercontent.com/1094740/34681357-845f9146-f493-11e7-9cb1-73aeb4c118dc.jpg)

If you need any extra info just gimme a shout :)

Love the hard work btw! much appreciated!

**Comment by daylerees** [comment]
Hi there! Would you mind trying the latest version? I think I might have fixed this. Let me know if it doesn't and I know how to for sure. :) Thanks!

**Comment by samrap** [comment]
I can confirm the update works for me! (was having the same issue)

**Comment by daylerees** [comment]
Awesome :) that's my favourite kind of issue! Enjoy fellas.

**Comment by OwenMelbz** [comment]
hey @samrap don't hijack my issue lol I am **UN**confirming as not fixed for me :( @daylerees 

![hmm](https://media.tenor.com/images/de7474c270bcceb340c06bad6df8d08e/tenor.gif)

Just pulled the latest version 

![rainglow_ _owen_batman](https://user-images.githubusercontent.com/1094740/34721097-4bd10d86-f539-11e7-99be-3ffcf9af7b5c.jpg)

Still got blacks

![___gitignore_ _winsor_bishop](https://user-images.githubusercontent.com/1094740/34721131-786691fe-f539-11e7-81a3-e7fcffc9b288.jpg)

**Comment by daylerees** [comment]
Haha! Mind sending me a sample file I can use to replicate this if that's ok mate?

**Comment by daylerees** [comment]
Ping @OwenMelbz :)

Sorry, but do you mind sending me a file to reproduce this issue? I'm on a bug hunt today :)

TY!

**Comment by OwenMelbz** [comment]
Ah sorry, got side tracked with Assassins creed this weekend!

Will check again soon, I’m gonna reinstall via package manager also :)

**Comment by daylerees** [comment]
Awesome, no problem! Huge fan of AC here. Going to assume Origins, enjoy!

**Comment by OwenMelbz** [comment]
Right I’m off my camel now.

I’ve reinstalled it all Through package manager and it seems all is good!

**Comment by daylerees** [comment]
That works for me! Thanks for checking! :)
